// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protobuf/schema.proto

package pubsubgateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ListenMessagesClient is the client API for ListenMessages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListenMessagesClient interface {
	HandleIncomingMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*ResponseIncominMessage, error)
}

type listenMessagesClient struct {
	cc grpc.ClientConnInterface
}

func NewListenMessagesClient(cc grpc.ClientConnInterface) ListenMessagesClient {
	return &listenMessagesClient{cc}
}

func (c *listenMessagesClient) HandleIncomingMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*ResponseIncominMessage, error) {
	out := new(ResponseIncominMessage)
	err := c.cc.Invoke(ctx, "/pubsubgateawy.ListenMessages/HandleIncomingMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListenMessagesServer is the server API for ListenMessages service.
// All implementations must embed UnimplementedListenMessagesServer
// for forward compatibility
type ListenMessagesServer interface {
	HandleIncomingMessage(context.Context, *IncomingMessage) (*ResponseIncominMessage, error)
	mustEmbedUnimplementedListenMessagesServer()
}

// UnimplementedListenMessagesServer must be embedded to have forward compatible implementations.
type UnimplementedListenMessagesServer struct {
}

func (UnimplementedListenMessagesServer) HandleIncomingMessage(context.Context, *IncomingMessage) (*ResponseIncominMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleIncomingMessage not implemented")
}
func (UnimplementedListenMessagesServer) mustEmbedUnimplementedListenMessagesServer() {}

// UnsafeListenMessagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListenMessagesServer will
// result in compilation errors.
type UnsafeListenMessagesServer interface {
	mustEmbedUnimplementedListenMessagesServer()
}

func RegisterListenMessagesServer(s grpc.ServiceRegistrar, srv ListenMessagesServer) {
	s.RegisterService(&ListenMessages_ServiceDesc, srv)
}

func _ListenMessages_HandleIncomingMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenMessagesServer).HandleIncomingMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pubsubgateawy.ListenMessages/HandleIncomingMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenMessagesServer).HandleIncomingMessage(ctx, req.(*IncomingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ListenMessages_ServiceDesc is the grpc.ServiceDesc for ListenMessages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListenMessages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pubsubgateawy.ListenMessages",
	HandlerType: (*ListenMessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleIncomingMessage",
			Handler:    _ListenMessages_HandleIncomingMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/schema.proto",
}
